# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.Word_Clock = QWidget()
        self.Word_Clock.setObjectName(u"Word_Clock")
        self.label = QLabel(self.Word_Clock)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 140, 91, 41))
        font = QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.iran_show_time_lb = QLabel(self.Word_Clock)
        self.iran_show_time_lb.setObjectName(u"iran_show_time_lb")
        self.iran_show_time_lb.setGeometry(QRect(310, 140, 151, 41))
        font1 = QFont()
        font1.setFamilies([u"DSEG7 Modern"])
        font1.setPointSize(18)
        self.iran_show_time_lb.setFont(font1)
        self.iran_show_time_lb.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.Word_Clock)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(160, 200, 101, 41))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.germany_show_time_lb = QLabel(self.Word_Clock)
        self.germany_show_time_lb.setObjectName(u"germany_show_time_lb")
        self.germany_show_time_lb.setGeometry(QRect(310, 200, 151, 41))
        self.germany_show_time_lb.setFont(font1)
        self.germany_show_time_lb.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.Word_Clock)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 260, 91, 41))
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.usa_show_time_lb = QLabel(self.Word_Clock)
        self.usa_show_time_lb.setObjectName(u"usa_show_time_lb")
        self.usa_show_time_lb.setGeometry(QRect(310, 260, 151, 41))
        self.usa_show_time_lb.setFont(font1)
        self.usa_show_time_lb.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.Word_Clock, "")
        self.Alarm = QWidget()
        self.Alarm.setObjectName(u"Alarm")
        self.input_hour_text_alarm = QLineEdit(self.Alarm)
        self.input_hour_text_alarm.setObjectName(u"input_hour_text_alarm")
        self.input_hour_text_alarm.setGeometry(QRect(630, 50, 51, 51))
        font2 = QFont()
        font2.setFamilies([u"DSEG7 Modern"])
        self.input_hour_text_alarm.setFont(font2)
        self.label_6 = QLabel(self.Alarm)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(690, 50, 16, 41))
        font3 = QFont()
        font3.setPointSize(24)
        self.label_6.setFont(font3)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.input_minute_text_alarm = QLineEdit(self.Alarm)
        self.input_minute_text_alarm.setObjectName(u"input_minute_text_alarm")
        self.input_minute_text_alarm.setGeometry(QRect(710, 50, 51, 51))
        self.input_minute_text_alarm.setFont(font2)
        self.input_minute_text_alarm.setAlignment(Qt.AlignCenter)
        self.add_alarm_button = QPushButton(self.Alarm)
        self.add_alarm_button.setObjectName(u"add_alarm_button")
        self.add_alarm_button.setGeometry(QRect(710, 120, 51, 41))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(False)
        self.add_alarm_button.setFont(font4)
        self.gridWidget = QWidget(self.Alarm)
        self.gridWidget.setObjectName(u"gridWidget")
        self.gridWidget.setGeometry(QRect(10, 10, 521, 531))
        self.grid_layout_alarm = QGridLayout(self.gridWidget)
        self.grid_layout_alarm.setObjectName(u"grid_layout_alarm")
        self.input_title_linetext = QLineEdit(self.Alarm)
        self.input_title_linetext.setObjectName(u"input_title_linetext")
        self.input_title_linetext.setGeometry(QRect(550, 11, 211, 31))
        self.tabWidget.addTab(self.Alarm, "")
        self.Stop_Watch = QWidget()
        self.Stop_Watch.setObjectName(u"Stop_Watch")
        self.stop_stopwatch_button = QPushButton(self.Stop_Watch)
        self.stop_stopwatch_button.setObjectName(u"stop_stopwatch_button")
        self.stop_stopwatch_button.setGeometry(QRect(430, 370, 171, 51))
        font5 = QFont()
        font5.setPointSize(24)
        font5.setWeight(QFont.ExtraLight)
        self.stop_stopwatch_button.setFont(font5)
        self.start_stopwatch_button = QPushButton(self.Stop_Watch)
        self.start_stopwatch_button.setObjectName(u"start_stopwatch_button")
        self.start_stopwatch_button.setGeometry(QRect(180, 370, 171, 51))
        self.start_stopwatch_button.setFont(font5)
        self.show_stopwatch_label = QLabel(self.Stop_Watch)
        self.show_stopwatch_label.setObjectName(u"show_stopwatch_label")
        self.show_stopwatch_label.setGeometry(QRect(240, 150, 311, 81))
        font6 = QFont()
        font6.setFamilies([u"DSEG7 Modern"])
        font6.setPointSize(36)
        self.show_stopwatch_label.setFont(font6)
        self.show_stopwatch_label.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.Stop_Watch, "")
        self.Timer = QWidget()
        self.Timer.setObjectName(u"Timer")
        self.input_hour_text = QLineEdit(self.Timer)
        self.input_hour_text.setObjectName(u"input_hour_text")
        self.input_hour_text.setGeometry(QRect(270, 170, 61, 51))
        font7 = QFont()
        font7.setFamilies([u"DSEG7 Modern"])
        font7.setPointSize(24)
        self.input_hour_text.setFont(font7)
        self.input_hour_text.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.Timer)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(340, 170, 16, 41))
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.Timer)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(430, 170, 16, 41))
        self.label_4.setFont(font3)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.input_minute_text = QLineEdit(self.Timer)
        self.input_minute_text.setObjectName(u"input_minute_text")
        self.input_minute_text.setGeometry(QRect(360, 170, 61, 51))
        self.input_minute_text.setFont(font7)
        self.input_minute_text.setAlignment(Qt.AlignCenter)
        self.input_second_text = QLineEdit(self.Timer)
        self.input_second_text.setObjectName(u"input_second_text")
        self.input_second_text.setGeometry(QRect(450, 170, 61, 51))
        self.input_second_text.setFont(font7)
        self.input_second_text.setAlignment(Qt.AlignCenter)
        self.start_timer_button = QPushButton(self.Timer)
        self.start_timer_button.setObjectName(u"start_timer_button")
        self.start_timer_button.setGeometry(QRect(260, 270, 81, 41))
        self.reset_input_timer_button = QPushButton(self.Timer)
        self.reset_input_timer_button.setObjectName(u"reset_input_timer_button")
        self.reset_input_timer_button.setGeometry(QRect(450, 270, 81, 41))
        self.tabWidget.addTab(self.Timer, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Clock", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"iran", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"germany", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"usa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Word_Clock), QCoreApplication.translate("MainWindow", u"Word Clock", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.add_alarm_button.setText(QCoreApplication.translate("MainWindow", u"add", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Alarm), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.stop_stopwatch_button.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.start_stopwatch_button.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.show_stopwatch_label.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Stop_Watch), QCoreApplication.translate("MainWindow", u"Stop Watch", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.start_timer_button.setText(QCoreApplication.translate("MainWindow", u"start", None))
        self.reset_input_timer_button.setText(QCoreApplication.translate("MainWindow", u"reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timer), QCoreApplication.translate("MainWindow", u"Timer", None))
    # retranslateUi

